name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Do something more meaningful then publish artifacts
      - name: Archive build output
        run: "tar --dereference --directory . -cvf artifact.tar ."
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: artifact.tar